services:
  manigaussian:
    image: manigaussian:cu117
    container_name: manigaussian
    build:
      context: .
      dockerfile: ./Dockerfile

    # Project path inside container
    working_dir: /app

    environment:
      DISPLAY: ":4"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "all"

    stdin_open: true
    tty: true
    restart: unless-stopped

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app/
      - manigaussian_venv:/app/.venv

    ports:
      - "2403:6001"

    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129

    # Docker Compose v2 GPU support
    gpus: all

    # # Increase shared memory to avoid Bus error from PyTorch multiprocessing
    # shm_size: '32gb'
    # ipc: host

    # Default startup command (interactive shell)
    command: /bin/bash

volumes:
  manigaussian_venv: